// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookmarksController from "./bookmarks_controller"
application.register("bookmarks", BookmarksController)

import ImagesController from "./images_controller"
application.register("images", ImagesController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)
